version: "3.2"

services:
  test-db:
    restart: always
    image: postgres:10.12-alpine
    command: ["postgres", "-c", "log_statement=all"]
    environment:
      POSTGRES_USER: "vdbm"
      POSTGRES_DB: "vulcanize_testing"
      POSTGRES_PASSWORD: "password"
    ports:
      - "127.0.0.1:8066:5432"
