name: Publish Docker image
on:
  release:
    types: [published]
jobs:
  build:
    name: Run docker build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Get the version
        id: vars
        run: |
          echo ::set-output name=sha::$(echo ${GITHUB_SHA:0:7})
          echo ::set-output name=tag::$(echo ${GITHUB_REF#refs/tags/})
      - name: Run docker build
        run: make docker-build
      - name: Tag docker image
        run: docker tag vulcanize/ipld-eth-beacon-db docker.pkg.github.com/vulcanize/ipld-eth-beacon-db/ipld-eth-beacon-db:${{steps.vars.outputs.sha}}
      - name: Tag docker image
        run: docker tag docker.pkg.github.com/vulcanize/ipld-eth-beacon-db/ipld-eth-beacon-db:${{steps.vars.outputs.sha}} docker.pkg.github.com/vulcanize/ipld-eth-beacon-db/ipld-eth-beacon-db:${{steps.vars.outputs.tag}}
      - name: Docker Login
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login https://docker.pkg.github.com -u vulcanize --password-stdin
      - name: Docker Push
        run: docker push docker.pkg.github.com/vulcanize/ipld-eth-beacon-db/ipld-eth-beacon-db:${{steps.vars.outputs.sha}}
      - name: Docker Push to Docker Hub
        run: docker push docker.pkg.github.com/vulcanize/ipld-eth-beacon-db/ipld-eth-beacon-db:${{steps.vars.outputs.tag}}
